name:  Build x86 and arm Image

env:
  BASEIMAGE: k8s.gcr.io/debian-base-amd64:v2.0.0
  TAG: v0.8.21

on:
  pull_request:
    branches:
      - ecx-*
      - develop
  push:
    branches:
      - ecx-*
      - develop

jobs:
  docker-image-production:
    if: startsWith(github.ref_name, vars.PRO_BRANCH)
    env:
      REGISTRY: ${{ vars.PRO_REGISTRY }}
    name: Build x86 and arm Image production
    runs-on: 
      group: Default
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.PRO_HARBOR_USERNAME }}
          password: ${{ secrets.PRO_HARBOR_TOKEN }}
      - name: Build & Push Docker image
        run: make push-container
  docker-image-develop:
    if: startsWith(github.ref_name, vars.DEV_BRANCH)
    env:
      REGISTRY: ${{ vars.DEV_REGISTRY }}
    name: Build x86 and arm Image develop
    runs-on: 
      group: Default
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DEV_HARBOR_USERNAME }}
          password: ${{ secrets.DEV_HARBOR_TOKEN }}
      - name: Build & Push Docker image
        run: make push-container
